[package]
name = "services"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
uuid = {version = "1.18", features = ["v5"]}
tracing = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

ai-llm-service = { path = "../ai-llm-service" }

anyhow = { workspace = true }
