[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }

axum = "0.8"

services = { path = "../services" }
graph-prepare = { path = "../graph-prepare" }
codegraph-prep = { path = "../codegraph-prep" }
vector-lib = { path = "../vector-lib" }
rag-store = { path = "../rag-store" }

serde = { workspace = true }
anyhow = { workspace = true }
