[package]
name = "mr-ai-backend"
version = "0.1.0"
edition = "2024"
authors = ["Yeftifeyev Konstantin <zoxo@outlook.com>"]
license = "FSL-1.1"

[workspace]
members = [".", "ai-llm-service", "ai-review-engine", "api", "code-indexer", "git-context-engine", "project_code_store", "rag-base", "services"]

[dependencies]
api = { path = "api" }

tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ai-llm-service = { path = "./ai-llm-service" }

dotenvy = "0.15"

[workspace.dependencies]
tokio = { version = "1.47", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
anyhow = "1.0"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt",] }
reqwest = { version = "0.12"}
thiserror = "1.0"
colored = "3.0"
