[package]
name = "ai-llm-service"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true, features = ["json","brotli"] }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
